import type { Metadata } from "next";
import "../styles/globals.css";
import "../styles/nullstyle.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="min-h-screen flex flex-col bg-slate-900 text-white">
                <header>
                    <div className="container mx-auto">
                        <Link href="/">Main</Link>
                        <Link href="/about">About</Link>
                    </div>
                </header>
                <main className="w-full flex flex-col flex-grow flex-shrink-0 ">
                    {children}
                </main>
                <footer className="container mx-auto">Footer</footer>
            </body>
        </html>
    );
}
